### ISSUE TITLE
Add `duffle rewrite` command

### ISSUE THREAD

**Issue by technosophos** [deislabs/duffle#217]
This command is the first step toward an export/import workflow. I think we should implement it as a stand-alone because we don't necessarily _always_ want to export when we rewrite.

Here's an example of what I imagine the command would look like:

```console
$ duffle rewrite -f path/to/bundle.json technosophos.azurecr.io/foo
```

Here's an example source `bundle.json`:

```json
{
    "name": "hellohelm",
    "version": "0.1.0",
    "invocationImage": {
        "imageType": "docker",
        "image": "cnab/lakebase:latest"
    },
    "images": [
        {
            "name": "alpine",
            "uri": "technosophos/demo2alpine:0.1.0",
            "refs": [
                {
                    "path": "cnab/app/charts/alpine/values.yaml",
                    "field": "image.repository"
                }
            ]
        },
               {
            "name": "alpine",
            "uri": "quay.io/technosophos/something:0.2.0",
            "refs": [
                {
                    "path": "cnab/app/charts/alpine/values.yaml",
                    "field": "image.deployment"
                }
            ]
        }
    ],
    "parameters": {},
    "credentials": {}
}
```

Okay, my interpretation of the original proposal is that running hte above command on the above `bundle.json` should do the following:

- The arg[1] should be interpreted as "rewrite the repo half of a a docker image to `technosophos.azurecr.io/foo`'
- The invocation image should be rewritten to `technosophos.azurecr.io/foo/lakebase:latest`
- The first and second image should be rewritten to:
 - `technosophos.azurecr.io/foo/demo2alpine:0.1.0`
- `technosophos.azurecr.io/foo/something:0.2.0`
- The file `cnab/app/charts/alpine/values.yaml` should be opened and following two things should be replaced:
  - `image.deployment` should be set to `technosophos.azurecr.io/foo/something:0.2.0`
  - `image.repository should be set to `technosophos.azurecr.io/foo/demo2alpine:0.1.0`

So the resulting `bundle.json` should be:

```json
{
    "name": "hellohelm",
    "version": "0.1.0",
    "invocationImage": {
        "imageType": "docker",
        "image": "technosophos.azurecr.io/foo/lakebase:latest"
    },
    "images": [
        {
            "name": "alpine",
            "uri": "technosophos.azurecr.io/foo/demo2alpine:0.1.0",
            "refs": [
                {
                    "path": "cnab/app/charts/alpine/values.yaml",
                    "field": "image.repository"
                }
            ]
        },
               {
            "name": "alpine",
            "uri": "technosophos.azurecr.io/foo/something:0.2.0",
            "refs": [
                {
                    "path": "cnab/app/charts/alpine/values.yaml",
                    "field": "image.deployment"
                }
            ]
        }
    ],
    "parameters": {},
    "credentials": {}
}
```

And the resulting cnab/app/charts/alpine/values.yaml should be:

```yaml
# Original stuff...

images:
  repository: technosophos.azurecr.io/foo/demo2alpine:0.1.0
  deployment: technosophos.azurecr.io/foo/something:0.2.0

# Other stuff from original values.yaml
```

We will need to decide in the future whose job it is to push the old images to the new location.

**Comment by glyn** [comment]
This issue corresponds to what we in the [riff project](https://projectriff.io/) call _image relocation_. For background, please see the design document [Private Docker Registries and riff](https://docs.google.com/document/d/1Y0wKbZWhOe2GlbZzksceKjxJhI1wxsgM8_IDCoq5gvs/edit?usp=sharing), the [riff issues labelled with `private-registry`](https://github.com/projectriff/riff/issues?q=label%3Aprivate-registry+is%3Aclosed), and the corresponding PRs.

In the context of CNAB, we see two possible approaches to image relocation:

1. Make image relocation the responsibility of an invocation image (probably packaged in a base invocation image and augmented with tooling). A parameter would specify the target registry and the invocation image would be responsible for tagging and pushing images to the target registry and rewriting kubernetes configuration files in the bundle to refer to the relocated image names. This approach puts the least burden on the CNAB spec and CNAB runtimes.

2. Make image relocation the responsibility of the CNAB runtime and pass a map from original image name to relocated image name to the invocation image so that it can rewrite kubernetes configuration files in the bundle to refer to the relocated image names. This approach puts the least burden on invocation images and tooling.

Image relocation could apply to thick bundles (probably most suited to an air gapped installation) or thin bundles (where the user has a network zone with read access to the internet and read-write access to the target registry).

[The above information refers to open source versions of `riff-distro` and `riff image` commands, but these have been moved to closed source. See the [PFS documentation](https://docs.pivotal.io/pfs/install-relocate-images.html) for usage information.]

**Comment by simonferquel** [comment]
Please note that we already implemented that in cnab-to-oci (see https://github.com/docker/cnab-to-oci/blob/master/remotes/fixup.go#L18).

**Comment by glyn** [comment]
@simonferquel Thanks for that. I couldn't find the code to update refs to images during fixup. Is that supported?

**Comment by glyn** [comment]
https://github.com/deislabs/duffle/issues/668 aims to add image relocation support.

**Comment by simonferquel** [comment]
@glyn https://github.com/docker/cnab-to-oci/blob/master/remotes/fixup.go < this is where it happens (it does multiple things: 
- for each image / invocation image, 
- it copies/mount manifests and blobs to the target repository
- it modifies the bundle structure to point to the new reference

At the end of the process, the push logic converts the bundle into an OCI index representation and pushed it to the registry

The pull logic parses this OCI index into a duffle bundle structure with all image references being digested and pointing to the same repository

**Comment by jeremyrickard** [comment]
I believe this should be closed in support of image relocation should it not?
