### ISSUE TITLE
Electron Installer

### ISSUE THREAD

**Issue by wahabshah** [deislabs/duffle#595]
I just have a question regarding the `Electron installer` which interfaces with the CNAB bundles for offline installations
[Source](https://techcrunch.com/2018/12/04/microsoft-and-docker-team-up-to-make-packaging-and-running-cloud-native-applications-easier/)
> Microsoft also today launched Visual Studio extension for building and hosting these bundles, as well as an example implementation of a bundle repository server and an **Electron installer** that lets you install a bundle with the help of a GUI.

Cant seem to find it in the source code of this repo or is it not yet released?

**Comment by technosophos** [comment]
Sorry, that was my fault. I made a last-minute decision to hold off on it because we had a couple of bugs that made it really hard to use. I didn't want everyone's first experience with it to be painfully difficult. I'll check in again with the team and see where we stand.

Again, I'm very sorry about that.

**Comment by technosophos** [comment]
It was released at KubeCon. Here's the link: https://github.com/deislabs/duffle-coat
