### ISSUE TITLE
Duffle show should format the bundle in a human-readable way

### ISSUE THREAD

**Issue by radu-matei** [deislabs/duffle#665]
With #612 merged, bundles are now represented in canonical form -- this means `duffle show` no longer formats the bundle in a human readable way:

```
$ duffle show canonical-test
{"credentials":null,"description":"A short description of your bundle","images":null,"invocationImages":[{"image":"deislabs/stateless-actions-cnab:e0fa4a7067b67884e7d352b735fa7d1335936cd5","imageType":"docker","platform":{}}],"keywords":["stateless-actions","cnab","tutorial"],"maintainers":[{"email":"john.doe@example.com","name":"John Doe","url":"https://example.com"},{"email":"jane.doe@example.com","name":"Jane Doe","url":"https://example.com"}],"name":"canonical-test","parameters":null,"version":"0.1.0"}
```

There are two ways to go about solving this:

- indenting the bundle in a human-readable way
- go further and not display the JSON file, but a table / TSON / other format, thus not exposing the underlying format to the users.

I think that first we should correctly indent the file, then discuss whether to move away from printing JSON.

**Comment by squillace** [comment]
@radu-matei thanks (@jeremyrickard). So, this isn't a problem for `duffle show` it's a serious problem for the developer experience in duffle. the Duffle.json file should not be in canonical form at all. 

ready? in duffle version 0.2.0-beta.3, the `duffle create` command gives the following duffle.json file:

![image](https://user-images.githubusercontent.com/1422718/62099985-bc688f00-b244-11e9-8220-7c777736f9d0.png)

so that if you build it, and THEN do a `duffle show`, the following is then the experience shown in the OP of the issue. Please evaluate this as you see fit, given that there are workarounds (pipe to `jq`, and so on).
