### ISSUE TITLE
CI is stuck again

### ISSUE THREAD

**Issue by michelleN** [deislabs/duffle#731]
closed out #729 bc Vaughn re-installed th eAzure Pipelines GitHub App and that seemed to do the trick. It's stuck again now.

@vdice if brigade is running our tests, do we need Azure Pipelines too? Maybe we should just stick with Brigade for now? What do you think?

**Comment by vdice** [comment]
To the first question, indeed, Azure Pipelines is duplicating what the Brigade pipeline is already covering, so perhaps we just uninstall.

Otherwise, I updated a current PR I have in this repo (to get latest from master), and after this completed, the Azure Pipelines check came in as expected: https://github.com/deislabs/duffle/pull/723

I wonder what the issue may be...

**Comment by michelleN** [comment]
gotchya yea it looks like it's working again!! 🎉 
Idk what these intermittent issues are but I won't have time to debug until I get back from SF. I think we should disable Azure Pipelines for now so we prevent blockers and since Brigade is doing the same checks. Would that be alright with you?

**Comment by vdice** [comment]
Sounds great.  I've disabled the Azure Pipeline and so this check should no longer occur on PRs.  The same code checks remain/persist in the Brigade pipeline.
