### ISSUE TITLE
Implement output handling 

### ISSUE THREAD

**Issue by michelleN** [deislabs/duffle#747]
https://github.com/deislabs/cnab-spec/pull/133

**Comment by astrieanna** [comment]
It seems like there's a couple things to do here:

1. Store the outputs in a claim (and modify the definition of a claim to make room for that).
2. Add a command to dump the outputs to the screen (`duffle outputs <name of installation>`).

cc @jeremyrickard @ryanmoran @carolynvs @silvin-lubecki

**Comment by astrieanna** [comment]
In order to implement outputs in Duffle, they need to be produced by cnab-go. The tricky part of this is to get the output files from the drivers. In the Kubernetes driver, the Invocation Image is run as a Job. We've come up with a few options for how the driver might get the output files from `/cnab/app/outputs` in the container back to the (k8s client) driver code.

The simplest option would be to use a persistent volume. The driver could mount the volume at `/cnab/app/outputs` in the invocation image and then retrieve the contents after the image has run. However, we don't think the driver should assume or require that persistent volumes are available on all clusters.

The rest of these options assume that an emptyDir volume will be mounted at `/cnab/app/outputs` in the invocation container and that there will be a second "sidecar" container in the same pod that runs the invocation image to do some extra work in retrieving the output files. The containers need to be in the same pod so that they can share the emptyDir volume.

1.  The sidecar container is given a service account token with permission to write secrets. It uses this token to write a secret containing the paths and contents of all files written by the invocation image (when that container finishes running).
  **Challenges**: This requires setting up a service account with the desired permissions; it's not clear that the Duffle driver expects to have those permissions already or that it would be better to ask users to setup this service account in advance.  The sidecar container will also need to figure out when the other container in the pod has finished, so that it can write the final state of the files to the secret.

2. The sidecar container could be used to just keep the pod running, so that the driver could use the API equivalent of `kubectl exec` to grab the output files from the volume.
  **Challenges**: The invocation image is run in a Job; the driver waits for the Job to finish. For the Job to finish, the Pod needs to exit, which means the containers need to exit. This sidecar would prevent that -- meaning a significant restructuring of how the driver waits for invocation image completion would be required.

3. The sidecar container could use its log to output the files from the output volume. This would require choosing some format that can be written to the stdout stream yet is easily parsed into a number of arbitrary binary files.
  **Challenges**: Picking a good format, complicates log stream logic in driver, seems ugly, could hit log size limit edge cases.

4. The sidecar container is a file server. The driver requests each expected output file over https from the sidecar when the invocation image finishes.
  **Challenges**: The sidecar does not exit when the invocation image does, which ruins the waiting for the Job to exit logic. There is no guarantee that the driver can connect to the pod directly (it appears to only talk to the API server so far), so connecting and/or securing the connection could be an issue.

All of these approaches have drawbacks, and there are likely some (of both) that we have not thought of.

cc @youreddy to complete the we

**Comment by glyn** [comment]
Nice summary @astrieanna!

> However, we don't think the driver should assume or require that persistent volumes are available on all clusters.

It would be good to describe why not. PVs would seem to solve a lot of the problems...

> 3. The sidecar container could use its log to output the files from the output volume. This would require choosing some format that can be written to the stdout stream yet is easily parsed into a number of arbitrary binary files.
>    **Challenges**: Picking a good format, complicates log stream logic in driver, seems ugly, could hit log size limit edge cases.

How about tar format?

**Comment by astrieanna** [comment]
The major problem that I see with PVs is that support is inconsistent across clusters. In order for a cluster to support PersistentVolumeClaims, you need to provide and have configured some underlying storage mechanism. This does work out of the box on new clusters on the major cloud providers (GKE, AKS, EKS): they provide their storage as a default StorageClass so creating a PVC just works.

For clusters that are not in public cloud KaaS, I expect the story to be much more varied, depending on whether the operator has previously had a need for PVCs or has storage they wish to provide this way. One example of clusters that I would not expect to support PVCs would be kind clusters commonly used in CI systems.

**Comment by jeremyrickard** [comment]
I've updated the title of this to reflect the actual behavior we want. This should be handled in `duffle` by #815.

**Comment by jeremyrickard** [comment]
From a _duffle_ stand point, I think we're done with this issue now. There remains some work to implement _fetching_ the outputs in the Command Driver and the Kubernetes driver, but I think _this one_ is done?

**Comment by astrieanna** [comment]
@jeremyrickard Do you wanna close this issue? I do not have the power.
