### ISSUE TITLE
duffle.json references

### ISSUE THREAD

**Issue by michelleN** [deislabs/duffle#751]
In some places `duffle.json` is referred to as the duffle config file and in other places, it is referred to as the duffle manifest. We should pick one and stick with it across documentation, code and error descriptions.

The floor is now open for naming opinions. 💁

**Comment by carolynvs** [comment]
For context, porter calls porter.yaml (or any eventual variation) a manifest. Is the `bundle.json` a manifest? At one point I thought it was but now I'm grepping the spec and in some places it says manifest (mostly in the registry media type) and the rest of the lace it doesn't use that.

I had originally called porter's file a manifest because it was porter's representation of the bundle manifest. Now I'm wondering if we goofed?

**Comment by technosophos** [comment]
`duffle.json` is a configuration file that tells Duffle how to build a bundle descriptor and the associated images. It is not a manifest because it is not an enumeration of the constituent parts of a bundle.

**Comment by glyn** [comment]
Now this is decided, flagging as good first issue.
