### ISSUE TITLE
duffle.json vs. duffle.toml

### ISSUE THREAD

**Issue by michelleN** [deislabs/duffle#752]
When we started the project. The file that contained configuration needed to build a bundle was called the `duffle.toml` file. We also decided to use `viper` to support `json`, `toml`, and `yaml` file types. We later had a conversation around standardizing on `duffle.json`. I don't recall what the end result was. Are we still supporting all three formats or did we decide to standardize on `.json` across the board? cc/ @carolynvs @itowlson

**Comment by carolynvs** [comment]
I just looked through the duffle manifest and all the mapstructure tags are still in place to support both encoding/json and viper.

Ralph has suggested that extra CLI usability concerns (read: maintenance overhead) can go into porter so that it's not something that we need to spend extra dev time on in duffle. I'm not sure how you view being able to use multiple markup languages with duffle? Seems like the support is there, so it's a matter of documentation (and some tests to make sure that it doesn't get broken accidentally down the road).

**Comment by technosophos** [comment]
Just do JSON. Most of our usability focus has now shifted to Porter. The goal for Duffle's building tools at this point is to exhibit how the artifacts in the spec are meaningfully used to build a bundle. So it is fine to treat `duffle build` as an expert case, useful to people who have read the specification.
